### ISSUE TITLE
Read password from STDIN

### ISSUE THREAD

**Issue by johanbrandhorst** [aead/minisign#11]
Hi,

It would be great to be able to read the password from STDIN, both for the initial key generation, and for signature creation. It appears the original supports this (from https://github.com/jedisct1/minisign/issues/43), while this implementation currently errors with `Error: failed to read password: inappropriate ioctl for device`.

**Comment by aead** [comment]
@johanbrandhorst Thanks for pointing this out 👍 - PR #12  fixes this by adding support for reading passwords from STDIN when generating / re-creating keys and signing messages.
