### ISSUE TITLE
Can you update the package name of go.mod

### ISSUE THREAD

**Issue by hailaz** [aead/minisign#27]
go: aead.dev/minisign@v0.2.0: unrecognized import path "aead.dev/minisign": reading https://aead.dev/minisign?go-get=1: 404 Not Found

https://github.com/minio/selfupdate/issues/12

**Comment by aead** [comment]
This is not related to the module name. You have to clean your go mod cache and set your GOPROXY env var, `GOPROXY=https://goproxy.cn,direct/`
